name: build and push  


on:
  push:
    branches: 
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Docker build and push 
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t raphaelsiston/vagrant-ansible-common02:latest .
          docker push raphaelsiston/vagrant-ansible-common02:latest
